name: volttron-py312
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - wheel
  - pyzmq
  - gevent
  - grequests
  - requests
  - idna >=2.5, <3
  - ply
  - psutil
  - python-dateutil
  - pytz
  - PyYAML
  - setuptools
  - tzlocal
  - cryptography
  - watchdog-gevent
  - deprecated

